### ISSUE TITLE
Question: Is msr-safe supported on Linux ARM64 ?

### ISSUE THREAD

**Issue by martin-g** [LLNL/msr-safe#129]
Hello,

I am trying to figure out whether msr-safe is supposed to work on ARM64/aarch64.
Neither CentOS/RockyLinux (via `kernel-headers` package) nor Ubuntu (via `linux-libc-dev`) provide `/usr/include/asm/msr.h` in their ARM64 packages.

Thank you!

**Comment by rountree** [comment]
Hi @martin-g,


I think it's unlikely to find MSRs on an Arm processor.  I don't know of any Arm-based architectures that have implemented MSRs and, as you've discovered, the Linux kernel folks aren't supporting MSRs on the Arm architecture either. 

That said, Arm only sells IP, and a the entity that is actually paying to fab the processor is free to add whatever features they like.  If you know of a specific Arm chip that does have rdmsr/wrmsr instructions, I'd be happy to work with you getting msr-safe to work on that platform.

**Comment by rountree** [comment]
Following up:  Arm does implement system registers and has specific instructions to read and write them.  Let us know if having access to these registers via an extension of msr-safe would be useful.

https://developer.arm.com/documentation/den0024/a/ARMv8-Registers/System-registers

**Comment by martin-g** [comment]
Hi @rountree !

Thank you for your answer!
I think that adding support for ARMv8 (aka aarch64) would be great!

**Comment by rountree** [comment]
@martin-g 
Can you tell us something about the use case you have in mind?  How are you currently accessing those registers, and how does giving regular users access to them make your life easier?  Is not having user space access holding up a project?

We need to allocate resources on this end, and that's easier if we have a story as to how new features will be helpful.

**Comment by martin-g** [comment]
Hi @rountree !

I came here because I noticed that the `msr-safe` component in [OpenHPC](https://github.com/openhpc/ohpc/tree/2.x/components/perf-tools/msr-safe) is disabled for Linux aarch64 setups.
I am not sure how exactly it is being used by OpenHPC!
I help making it possible to run/use OpenHPC on openEuler OS 22.03 aarch64 and msr-safe was one of the components that fails to build due to a missing `#include <asm/msr.h>` on Linux aarch64.

**Comment by rountree** [comment]
@martin-g 
So msr-safe is properly disabled in OpenHPC since there aren't MSRs (strictly defined) on that platform.  Making msr-safe useful on that platform is going to be much more involved that creating a single header file.  If there's a need for it, of course, we're happy to have a discussion.  But for what you're doing, I think the correct answer is to mark msr-safe has x86-specfic code and leave it out of your Arm build.

**Comment by martin-g** [comment]
OK! Thank you, @rountree !
