### ISSUE TITLE
msrsave: Print changes on restore

### ISSUE THREAD

**Issue by bensallen** [LLNL/msr-safe#23]
Requesting a new feature of msrsave. 

On restore, print the changes. Including the MSR changed, old value, and optionally the new value. We're interested in using this functionality at job end, when we restore a set of default values on nodes, to provide internal logging of what users are doing with msr-safe. Ideally the output printed should be easily machine parsable, i.e JSON, CSV, etc.

**Comment by bensallen** [comment]
@cmcantalupo Any chance you can take a look at this?

**Comment by cmcantalupo** [comment]
Should be pretty easy to implement this feature.  I'll take a look into it later this week.

**Comment by cmcantalupo** [comment]
@bensallen 

Quick patch to add this output to msrsave is here:

https://github.com/cmcantalupo/msr-safe/tree/cmcantalupo-print-restore
https://github.com/LLNL/msr-safe/pull/27

Let me know if you have any comments or questions.
