### ISSUE TITLE
->i_mutex is replaced with ->i_rwsem on kernel 4.7

### ISSUE THREAD

**Issue by fblagojevic** [LLNL/msr-safe#26]
The module fails to compile on kernel 4.7 and up because ->i_mutex is replaced with ->i_rwsem. Simple fix would be to replace mutex_lock() with inode_lock() in msr_entry.c .

**Comment by slabasan** [comment]
This issue should be resolved with this commit: 5adfe7. I am closing this issue, but please let us know if the module continues to fail on kernel v4.7.
