### ISSUE TITLE
Cannot get max non-turbo ratio and minimum ratio because register in whitelist missing

### ISSUE THREAD

**Issue by TomTheBear** [LLNL/msr-safe#32]
I didn't checked all but some whitelists (0645, 0646, 0657 and not yet added 064F) are missing the register MSR_PLATFORM_INFO which contains some values required to calculate the clock of the invariant TSC and the minimal clock speed. 

Since the bits are read-only, an empty write mask is required:
0x000000CE  0x0000000000000000  # "SMSR_PLATFORM_INFO"

P.S. The title is wrong, I thought it the number of turbo ratio limits that is inside there but it's some frequencies

**Comment by slabasan** [comment]
Hi @TomTheBear, thank you for your feedback. If you don't mind, I'm going to update the title of this issue to better match your comment.
