### ISSUE TITLE
No current support for Kaby Lake.

### ISSUE THREAD

**Issue by rmdcoding** [LLNL/msr-safe#35]
Is it possible to get a Kaby Lake specific whitelist for msr-safe?

**Comment by rountree** [comment]
@rmdcoding 
No idea if you're still out there, but we still do not have support for Kaby Lake.

**Comment by rmdcoding** [comment]
@rountree I did Intel ever release a whitelist for Kaby Lake specific registers?

**Comment by rountree** [comment]
@rmdcoding Intel didn't release those---that was our work.  Intel wouldn't go on record saying any particular msr was "safe," and that makes sense:  what matters is the entire environment.

If you're still interested in a Kaby Lake allowlist it wouldn't be hard to whip one up that's useful for our environment.  That may be a good enough place for you to start.

I have another ongoing project that should let us automate allowlist generation, but that's probably a few weeks out.

Apologies again for not getting back to you several years ago....

**Comment by TomTheBear** [comment]
Just got the notification for @rountree 's post.

@rmdcoding: There is not much difference between the Intel Skylake (SP) and Intel Kabylake at core-level and RAPL, so if you want to write your own allowlist, you could use https://github.com/LLNL/msr-safe/blob/main/allowlists/al_0655#L1-L62 as a starting point.
