### ISSUE TITLE
Issues when building msr-safe rpms

### ISSUE THREAD

**Issue by bne86** [LLNL/msr-safe#36]
Hi,
when using your specfile for building rpms, one has to add the dependency
> BuildRequires: systemd-units

to be able to build the rpms using mock.
He is not able to substitude _%{_unitdir}_ and  _%{_udevrulesdir}_ when the dependency is missing. See [this](https://lists.fedoraproject.org/pipermail/devel/2011-November/160100.html).

**Comment by slabasan** [comment]
@bne86 -- I have added the dependency to the RPM spec here: [https://github.com/slabasan/msr-safe/tree/slabasan-rpm-unitdir-udevrulesdir](https://github.com/slabasan/msr-safe/tree/slabasan-rpm-unitdir-udevrulesdir)

+@cmcantalupo @bensallen: Can you double check that this fixes the build?

**Comment by bensallen** [comment]
It probably makes sense to require “systemd” instead of “systemd-units”. The latter is provided by the systemd package, so it’s a bit more clear to require the package itself.

**Comment by bne86** [comment]
I would suggest to add the requirement in a second line.
And, why not keep the build-environment as slim as possible and use "systemd-units"? If using a build environment that always starts from scratch, this would reduce the unnecessary overhead.

**Comment by bensallen** [comment]
The systemd-units build requirement is being fulfilled by the systemd RPM. There is no difference in using one name over the other in this spec file except for readability. The actual build dependency this ticket is about is the missing systemd rpm macros, which has little todo with unit files, so systemd-units is less descriptive of the actual requirement.

**Comment by slabasan** [comment]
I added in the missing dependency, using systemd vs systemd-units, as suggest above. Thanks to everyone for your input!
