### ISSUE TITLE
OpenHPC distribution of msr-safe

### ISSUE THREAD

**Issue by cmcantalupo** [LLNL/msr-safe#39]
I'm working on getting msr-safe integrated with the OpenHPC distribution for supporting the GEOPM integration with OpenHPC:

<https://github.com/cmcantalupo/ohpc/tree/cmcantalupo-geopm>
<https://build.openhpc.community/package/show/home:cmcantalupo/msr-safe>

Any comments or suggestions are welcome, especially from @bensallen.  

Thanks!

**Comment by bensallen** [comment]
Quickly looked over it, seems reasonable to me. Note, I haven't actually integrated anything into OpenHPC.

**Comment by cmcantalupo** [comment]
Thanks Ben.  I have created a pull request for msr-safe and geopm inclusion in OpenHPC here:

https://github.com/openhpc/ohpc/pull/747

Note I have added the patch referenced in issue #38 to the spec file to make the wmask an input parameter to the ioctl().  If the community here prefers, I can leave this patch out of the pull request.

**Comment by slabasan** [comment]
Looks good to me, but I also do not have any experience integrating into OpenHPC.

Referring to issue #38 -- my vote would be to leave it out of the PR for now. I'd like to spend some cycles testing on our side to double check there are no implications elsewhere in the kernel by changing from an output to an input parameter.
