### ISSUE TITLE
Getting Erros during make

### ISSUE THREAD

**Issue by narendra-cs** [LLNL/msr-safe#41]
I fired 

 CPPFLAGS="-I/usr/src/kernels/2.6.32-696.20.1.el6.x86_64/include -I$PWD -I$PWD/msrsave" make

inside of msr-safe directory and getting following errors:

cc  -I/usr/src/kernels/2.6.32-696.20.1.el6.x86_64/include -I/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe -I/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msrsave   -c -o msrsave/msrsave.o msrsave/msrsave.c
cc  -I/usr/src/kernels/2.6.32-696.20.1.el6.x86_64/include -I/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe -I/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msrsave   -c -o msrsave/msrsave_main.o msrsave/msrsave_main.c
cc   msrsave/msrsave.o msrsave/msrsave_main.o   -o msrsave/msrsave
make -C /lib/modules/2.6.32-696.20.1.el6.x86_64/build M=/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe modules
make[1]: Entering directory `/usr/src/kernels/2.6.32-696.20.1.el6.x86_64'
  CC [M]  /home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msr_entry.o
  CC [M]  /home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msr_whitelist.o
/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msr_whitelist.c: In function ‘find_in_whitelist’:
/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msr_whitelist.c:303:9: error: implicit declaration of function ‘hash_or_each_possible’ [-Werror=implicit-function-declaration]
         hash_or_each_possible(whitelist_hash, entry, node, hlist, msr);
         ^
/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msr_whitelist.c:303:60: error: ‘hlist’ undeclared (first use in this function)
         hash_or_each_possible(whitelist_hash, entry, node, hlist, msr);
                                                            ^
/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msr_whitelist.c:303:60: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
make[2]: *** [/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe/msr_whitelist.o] Error 1
make[1]: *** [_module_/home/cc/vfaculty/nsingh.vfaculty/software/tars/msr-safe] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.32-696.20.1.el6.x86_64'
make: *** [all] Error 2

Compiler : gcc-4.9.3
Kernel: 2.6.32-696.20.1.el6.x86_64

**Comment by slabasan** [comment]
Hi @narendra-cs, my guess is that `hash_or_each_possible` should have been `hash_for_each_possible`. I have made this change and pushed it to a branch on my fork here: `https://github.com/slabasan/msr-safe/tree/slabasan-fix-error-v2_6_32`. Can you give this version a try and see if that resolves the make errors?
