### ISSUE TITLE
whitelist for wl_064e

### ISSUE THREAD

**Issue by markpsycho** [LLNL/msr-safe#42]
wl_file for my computer  is wl_064e, where to get this file as it is not in whitelists folder.
Also How these whitelists are made, can I make it by by own by choosing which MSRs to access?

**Comment by slabasan** [comment]
Hi @markpsycho -- new whitelists are created for each Intel platform. We create these whitelists from the Intel SW Developer Manual, which will define the MSR addresses and specific bit fields for your particular architecture. You can create your own whitelist with the MSRs you want and load it into the msr_whitelist with `cat <your_whitelist> > /dev/cpu/msr_whitelist`. If you do make your own whitelist for `wl_0643`, we would be happy to merge it in as a PR. If you have any questions about how to do this, please let me know.
