### ISSUE TITLE
Bizzare ENXIO when dealing with /dev/cpu/msr_whitelist

### ISSUE THREAD

**Issue by fearful-symmetry** [LLNL/msr-safe#43]
I try not to file issues before I can be 100% that it's not something I'm doing, but I'm pretty lost.

We have msr-safe installed across our compute cluster. Once in a blue moon, the `msr-safe` init script seems to fail:
`Aug 10 17:15:08 nid04370 msr-safe[5812]: /usr/sbin/msr-safe: line 19: /dev/cpu/msr_whitelist: No such device or address`

This is where things get weird:

```
stat /dev/cpu/msr_whitelist 
  File: '/dev/cpu/msr_whitelist'
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 6h/6d   Inode: 21126       Links: 1     Device type: f0,0
Access: (0660/crw-rw----)  Uid: (    0/    root)   Gid: (  476/     msr)
Access: 2018-08-10 17:15:08.352126407 +0000
Modify: 2018-08-10 17:15:08.352126407 +0000
Change: 2018-08-10 17:15:08.352126407 +0000
 Birth: -

cat /usr/share/msr-safe/whitelists/wl_0657 >> /dev/cpu/msr_whitelist
-bash: /dev/cpu/msr_whitelist: No such device or address

cat /dev/cpu/msr_whitelist
cat: /dev/cpu/msr_whitelist: No such device or address

file /dev/cpu/msr_whitelist
/dev/cpu/msr_whitelist: character special (240/0)

```

Running `strace` gives a little hint: 
```
open("/dev/cpu/msr_whitelist", O_RDONLY) = -1 ENXIO (No such device or address)
```

The only way to fix this is to reload the module, and the failure _only_ seems to happen during a boot. It seems to happen only once in a couple hundred nodes, but we have a lot of nodes, so it's a problem. I can't reproduce the failure outside of boot; I've been running `systemctl restart` and `modprobe` and so on over and over in a loop, and it's always fine.

Next step is to deploy a version of msr-safe with `DDEBUG` compiled in. However, that's going to take time to deploy. For now, I'm filing this to see if anyone has some ideas.

**Comment by mcfadden8** [comment]
Is there anything useful provided by ```dmesg```?  

It sounds like the kernel module may have either failed to start or stopped for some reason.

**Comment by fearful-symmetry** [comment]
Not that I can find. It doesn't help that cray loves to pollute `dmesg` with random junk, but I can't find anything, hence me compiling with `DDEBUG` When that RPM gets applied in a few days, I'll check back in with any fun updates.

**Comment by slabasan** [comment]
Thanks for the feedback @fearful-symmetry! This is interesting behavior for sure. Please do keep us posted on any updates once the updated RPM is applied. We will try to provide guidance here. Is this on Theta? What are you using for the init script?

**Comment by fearful-symmetry** [comment]
@slabasan Yep, this is on theta.

We're using the init scripts you provide: https://github.com/LLNL/msr-safe/blob/master/rpm/msr-safe.sh

**Comment by fearful-symmetry** [comment]
So, we've deployed the module with DDEBUG turned on, and...nothing.

Crucially, the debug message that normally gets printed when you [write the whitelist](https://github.com/LLNL/msr-safe/blob/master/msr_whitelist.c#L122) isn't printed either. 

So, either something is breaking before that, or something else is interfering with the kernel module while it's being loaded.

**Comment by slabasan** [comment]
@fearful-symmetry Do you think we could set up a quick call? We would like to understand how you are deploying the kernel before we start trying to further debug.

**Comment by bgeltz** [comment]
@slabasan : @cmcantalupo and I would be happy to throw in our $0.02 on this issue if you're going to setup a call.

**Comment by slabasan** [comment]
@bgeltz @cmcantalupo Sure, happy to include all interested parties on the call. Any big conflicts for a possible meeting tomorrow?

**Comment by fearful-symmetry** [comment]
Tomorrow would work, any time after 2PM central time.

**Comment by cmcantalupo** [comment]
Tomorrow @ 2PM CDT works for me.  I think @bgeltz will be free then as well.

**Comment by bgeltz** [comment]
Yup!

**Comment by fearful-symmetry** [comment]
Alas, I do not have good news. When we rebooted Theta on Friday night, a small number of nodes (22) came up with `msr-safe` in a bad state. We've modified the init script, and the`start()` function now looks like this:

```bash
start() {
  if [ -z "${WL_CPU:-}" ]; then
    WL_CPU=$(printf 'wl_%.2x%x\n' "$(lscpu | grep "CPU family:" | awk -F: '{print $2}')" "$(lscpu | grep "Model:" | awk -F: '{print $2}')")
  fi

  if [ -z "${WHITELIST:-}" ]; then
    WHITELIST="/usr/share/msr-safe/whitelists/${WL_CPU}" 
  fi

  if [ -f "/usr/share/msr-safe/whitelists/${WL_CPU}" ]; then
    # /sbin/modprobe msr-safe && \
    # cat "${WHITELIST}" > /dev/cpu/msr_whitelist
    /sbin/modprobe msr-safe
    rc=$?
    if [ $rc -ne 0 ] ; then
      return $rc
    fi

    #before we do anything else, loop around to make sure msr_safe is in a good state
    begin=0
    #last cpu_id
    end=$(($(lscpu | grep ^CPU\(s\): | cut -d ":" -f 2 ) - 1))
    #loop over all cpus
    for i in $(seq $begin $end); do
        #check if msr_safe file exists
        while [ ! -e /dev/cpu/"$i"/msr_safe ]; do
            usleep 500000
            echo "/dev/cpu/$i/msr_safe not ready: sleeping 0.5s"
        done
    done


    #stat the file until it exists
    success=1
    for i in $(seq 1 5);
    do
      stat /dev/cpu/msr_whitelist >/dev/null 2>&1
      rc=$?
      if [ $rc -eq 0 ]; then
        success=0
        break
      fi
      sleep 1
    done

    if [ $success -ne 0 ]; then
      return 1
    fi

    cat "${WHITELIST}" > /dev/cpu/msr_whitelist


    return $?
  else
    return 1
  fi
}
```

I'm hardly a bash ninja, so I could be overlooking something, or the issue could be elsewhere.

**Comment by bgeltz** [comment]
What is the return code from this script?  @cmcantalupo was wondering if the ```cat "${WHITELIST}"``` line is being executed in the case where the driver does not come up properly.

I'm not sure if this is related to the issue we're chasing on Theta but:

I have previously seen issues where there was a stale /dev/cpu/msr_whitelist file that existed prior to the ```modprove msr-safe``` call.  In that scenario, the driver was not able to create the msr_whitelist file since it already existed.  The driver loaded successfully, but this stale whitelist file was not connected to the driver in any way.  In that case, I had to remove the stale file before msr-safe would function properly.  In my case, it turns out there was another service that was trying to write the whitelist at boot.  This race between the driver and this other service lead to the stale whitelist file.  I ended up removing this other service from the compute image to resolve the issue.

**Comment by fearful-symmetry** [comment]
Yah, the script fails when it reaches the `cat "${WHITELIST}" > /dev/cpu/msr_whitelist`

"his race between the driver and this other service lead to the stale whitelist file."

What other service was that?

**Comment by slabasan** [comment]
After the `modprobe msr-safe`, I think you want to check for the `msr_safe` kernel in `lsmod`. If this returns successfully, then every `/dev/cpu/$i/msr_safe` should exist, though you could keep your for loop as is to double check. Also, depending on how many nodes are running this at once during boot, you may want to increase the sleep time from 1 second to 5 seconds. What is the status of the msr-safe install on the nodes that failed? Has the module been loaded and the whitelist is bad? Or is the module not even loaded all together?

**Comment by fearful-symmetry** [comment]
On bad nodes, the module appears to be loaded according to `lsmod`. Once the cluster is up in a few hours, I can check again.

**Comment by bgeltz** [comment]
> What other service was that?

This was a custom service that our team wrote to set the whitelist at node boot.  This was an older solution for setting the whitelist that existed before the ```msr-safe.sh ``` script existed.

**Comment by fearful-symmetry** [comment]
I only see the actual ENXIO when I run `strace`

From systemd, all I see is `/usr/sbin/msr-safe: line 57: /dev/cpu/msr_whitelist: No such device or address` in the boot logs. Which is what you get when the `open()` to `cat` returns an ENXIO.

**Comment by bgeltz** [comment]
Re: https://github.com/LLNL/msr-safe/issues/43#issuecomment-413299537
> Crucially, the debug message that normally gets printed when you write the whitelist isn't printed either.
> 
> So, either something is breaking before that, or something else is interfering with the kernel module while it's being loaded.

This was the exact behavior I was seeing re:  https://github.com/LLNL/msr-safe/issues/43#issuecomment-416330353 and https://github.com/LLNL/msr-safe/issues/43#issuecomment-416312876.  As soon as I removed the file and reloaded the driver, I started seeing the debug messages about writing and reading the whitelist.

I'm wondering if something else is writing the whitelist file on Theta's compute nodes before the driver has created the special device file...

**Comment by fearful-symmetry** [comment]
Yah, the fact that I can only reproduce this during boot time would lend credence to that theory. I can't think of anything else that's touching msr-safe, but I can poke around. Unless you have some ideas.

**Comment by fearful-symmetry** [comment]
That's an interesting possibility. The compute images that the node boots into are created from scratch every few weeks, so it would have to be something in the RPM post scripts or the image build process.

**Comment by fearful-symmetry** [comment]
Minor update: After poking around, I can't seem to find anything that would try and load or create the whitelist device at boot time. It's a tantalizing  explanation, but I'm not sure where to look.

**Comment by mcfadden8** [comment]
Can you try modifying the start() function in your script to check for the existence of the /dev/cpu/msr_whitelist file **before** calling modprobe?  I am wondering whether the msr-safe module from a previous run either did not get unloaded succesfully or wound up in a bad state such that it could not be unloaded?

If /dev/cpu/msr_whitelist does exist at the earlier point in time, it would be great if you could log that information and attempt to unload it again and see if the unload is indeed failing.

**Comment by fearful-symmetry** [comment]
@mcfadden8 Ah, that's a good point. I had assumed that the issue stemmed from that `cat` while something was still loading/in a bad state, but that's a possibility. I'll see if I can get that changed on the next PM period.

**Comment by fearful-symmetry** [comment]
Alright, I'm gonna try adding this to the start of the start script's `start()` function:

```bash
  if [ -c "/dev/cpu/msr_whitelist"]; then
    echo "Character device at /dev/cpu/msr_whitelist already exists"
    return 1
  fi
```

**Comment by fearful-symmetry** [comment]
Another thing I just noticed:
`/dev/cpu/$CPU/msr_safe` actually still works. You can read/write to it as root no problem.

**Comment by slabasan** [comment]
You are able to read/write MSRs through `msr_safe` on a "bad" node? On this node, what is the output `cat /dev/cpu/msr_whitelist`? Is it identical to `/usr/share/msr-safe/whitelists/${WL_CPU}"`?

**Comment by fearful-symmetry** [comment]
Using my patched version of `rdmsr` that reads from `msr_safe` : 
```
nid01712:~ # cat /dev/cpu/msr_whitelist
cat: /dev/cpu/msr_whitelist: No such device or address
nid01712:~ # patched_rdmsr -X -0 -p 0 0x610
00478810001586B8
nid01712:~ # rdmsr -X -0 -p 0 0x610
00478810001586B8
```

**Comment by slabasan** [comment]
I believe if the user performs reads/writes as root, then the user has `CAP_SYS_RAWIO` privileges and is accessing the stock msr driver. In other words, you were able to successfully read with your `patched_rdmsr` binary without the whitelist (which does not exist on this node) since you had elevated privileges.

**Comment by mcfadden8** [comment]
Strange.

The sequence from ```mod-probe msr-safe``` is:
1. The module is kernel module is loaded
2. [msr_init](https://github.com/LLNL/msr-safe/blob/master/msr_entry.c#L341) is called.  
3. ```msr_init()``` calls [msrbatch_init()](https://github.com/LLNL/msr-safe/blob/master/msr_batch.c#L254) 
4. ```msrbatch_init()``` calls ```device_create()``` which causes the /dev/cpu/msr_batch character device file to be created.
5. ```msrbatch_init()``` returns to ```msr_init()```
6. ```msr_init()``` then calls [msr_whitelist_init()](https://github.com/LLNL/msr-safe/blob/master/msr_whitelist.c#L420)
7. ```msr_whitelist_init()``` calls ```device_create()``` which causes the /dev/cpu/msr_whitelist character device file to be created.
8. ```msr_whitelist_init() then returns to ```msr_init()```
9. ```msr_init()``` then calls [msr_device_create()](https://github.com/LLNL/msr-safe/blob/master/msr_entry.c#L281) for each CPU and creates the /dev/cpu/#/msr_safe character device files.
10. Then it returns to ```modprobe```

Error returns from each of the functions mentioned above are checked and the initialization process is stopped so modprobe would fail.

I would be willing to add some additional instrumentation to the msr-safe kernel module to help track this down if you are willing to build debug versions of the modified files and try them since I don't have a reproducible case here.

Let me know if this would be practical or not.

**Comment by fearful-symmetry** [comment]
Yah, added instrumentation is probably the next step, considering how difficult this is to debug, particularly as any patches need to go on our T&D system first, and then we have to wait for the next Maintenance period to put them on Theta

**Comment by mcfadden8** [comment]
Alright.  Let me see if I can put something together over the weekend.

**Comment by mcfadden8** [comment]
@fearful-symmetry, what version of Linux are you running?  Just checking.

**Comment by fearful-symmetry** [comment]
SLES 12 SP3, kernel 4.4.103

**Comment by mcfadden8** [comment]
I've added some instrumentation in the source code located in the [msr-enxio](https://github.com/LLNL/msr-safe/tree/msr-enxio) branch.  If you can either perform the build using the Makefile that is there or make sure to enabled "-DDEBUG" for CFLAGS_msr_whitelist.o, CFLAGS_msr_entry.o, and CFLAGS_msr_bach.o, I would be interested in seeing the output of ```dmesg | grep msr_safe``` on the node where the problem is reproduced.

Please let me know if you have any questions.

Thanks,

**Comment by fearful-symmetry** [comment]
Apologies for the delay, I've been on vacation.

We've applied the upstream patches from the the `msr-enxio` branch onto our TDS. Provided nothing breaks, we'll be throwing them on Theta soon.

**Comment by cmcantalupo** [comment]
Where are these messages coming from on the good node output?

```
[  477.662407] msr_safe: delete_whitelist: 
[  477.662411] msr_safe: delete_whitelist: Returning Early, Whitelist already empty
```

**Comment by fearful-symmetry** [comment]
Presumably the messages after the init log lines are from the systemd service `cat`ing the whitelist into `/dev/cpu/msr_whitelist`

**Comment by cmcantalupo** [comment]
delete_whitelist() is called here:
https://github.com/LLNL/msr-safe/blob/7fe73cd2eeabcb456ced6c59b512cee1e0e4aeb3/msr_whitelist.c#L126
with a lock applied but when the whitelist is being created:
https://github.com/LLNL/msr-safe/blob/7fe73cd2eeabcb456ced6c59b512cee1e0e4aeb3/msr_whitelist.c#L284
there is no lock being used.  I'm not sure if this could be an issue, or if there is any opportunity for a race here.

**Comment by cmcantalupo** [comment]
Thanks @fearful-symmetry, that makes sense.

**Comment by fearful-symmetry** [comment]
Oh, interesting catch!

**Comment by cmcantalupo** [comment]
I think the lock used in this situation is actually located here:
https://github.com/LLNL/msr-safe/blob/7fe73cd2eeabcb456ced6c59b512cee1e0e4aeb3/msr_whitelist.c#L177

**Comment by cmcantalupo** [comment]
I think the lock used in this situation is actually located here:
https://github.com/LLNL/msr-safe/blob/7fe73cd2eeabcb456ced6c59b512cee1e0e4aeb3/msr_whitelist.c#L177

**Comment by slabasan** [comment]
I've been doing some digging in on this late last week. I found it interesting that on the nodes where msr-safe failed to load, you get a successful return from msr_whitelist_init (which should create the `msr_whitelist` character device driver), but when you did `cat /dev/cpu/msr_whitelist` you got the `No device` error. 

I'm still trying to figure out what is going on, but I am looking at `device_create`, which appears to return success even if it cannot create `msr_whitelist`. We could manually check for the presence of these device files, but I think we will need to find a way to check for failure (of `msr_batch`, `msr_whitelist`, and `$d/msr_safe`) while the msr-safe module is being loaded. Will keep looking into this and will keep you posted. 

We're a bit stretched across projects at the moment, so apologies for the delay. Thanks for your patience.

**Comment by slabasan** [comment]
@fearful-symmetry : On one of the nodes that failed, are you able to share the contents of `ls -l /dev/cpu` and `ls -l /dev/char`? I am wondering if the device is not being correctly assigned a major/minor number.

**Comment by fearful-symmetry** [comment]
@slabasan running `ls /dev/cpu` on a knl node is a bit intimidating, so I stuck it in a gist: https://gist.github.com/fearful-symmetry/c8ef76727c5c3a1f7b3372379b741165

**Comment by cmcantalupo** [comment]
@slabasan @fearful-symmetry @bensallen Is issue #45 related to this issue?

**Comment by bensallen** [comment]
@cmcantalupo These are on difference systems, so not directly related. @fearful-symmetry and I were discussing if they might related, and I don't *think* so. #45 causes later (after msr-safe is loaded) kernel modules to not load, but msr-safe itself appears to always be able to pick an unused MAJOR number and load.

**Comment by cmcantalupo** [comment]
Thanks @bensallen

**Comment by slabasan** [comment]
@bensallen @fearful-symmetry : @rountree and I will be visiting Argonne on Wednesday. We were wondering if you might have time to discuss msr-safe and outstanding issues. I think our schedules are fairly open that day -- Barry will be giving a talk about msr-safe, but other than that, we should be free. Thanks!

**Comment by fearful-symmetry** [comment]
I have a meeting at 1:30 localtime. Other than that, I'll be free.

**Comment by slabasan** [comment]
Thanks @fearful-symmetry! Looking forward to meeting you later this week.

**Comment by fearful-symmetry** [comment]
Some fun and exciting updates after our IRL discussion the other day.

It looks like `msr_whitelist` is getting squashed by a cray device, `/dev/ukbridge0` that's part of "compatibility" package. The RPM describes it as such:
```
Driver that provides non-existent devices.
```

The kernel module that's responsible for the `/dev/ukbridge0` device is controlled by a systemd service that creates the char device using mknod:

```
mknod $FILE c $MAJOR $MINOR
```
An interesting tidbit: Although the major number 240 is coded into a script, an object dump of the kernel module reveals that it's also in the kernel module itself. Trying to change the major number through the init script results in a broken module. We're currently working on a case with Cray, and we'll see if we can either get the behavior changed, or if it's safe to disable the module entirely.

**Comment by bgeltz** [comment]
Given the above comment, is seems like this issue has been root caused.  Can we expect a fix to be rolled out soon?

**Comment by fearful-symmetry** [comment]
"expect" is probably an optimistic word, considering that this is Cray we're talking about. We have a case open, and I'm trying to get a response back as to the "approved" way to deal with Cray's package that's squashing msr-safe. My theory is that it can be removed completely, but I'm not 100% sure.

**Comment by bgeltz** [comment]
Sounds good.  Thanks for the update.

**Comment by bensallen** [comment]
@slabasan I think it is still useful to add a module parameter into msr-safe to allow configuration of the MAJOR number as this conflict problem exists on other platforms as well, eg. in #46.

**Comment by slabasan** [comment]
Sure, sounds good to me. The plan is the logic to be: if a parameter is specified then statically assign a major device number, otherwise dynamically select a major device number. I imagine we will want this logic for all 3 devices -- `msr_safe`, `msr_whitelist`, and `msr_batch`. This looks like a reasonable reference guide: https://www.tldp.org/LDP/lkmpg/2.6/html/x323.html.
