### ISSUE TITLE
Update msr-safe rpm

### ISSUE THREAD

**Issue by slabasan** [LLNL/msr-safe#49]
The msr-safe kernel now accepts parameters, so need to add support to the systemd scripts so someone can set parameters in the sysconfig file.

Migrated from PR #48: 
Should we use /etc/modprobe.conf or its equivalents instead of the init script's modprobe?

**Comment by rountree** [comment]
@slabasan Does this still need to be done?

**Comment by slabasan** [comment]
This was a nice-to-have feature, but not required. It's been so long, let's close this and re-open if someone asks for it.
