### ISSUE TITLE
New release for ISC?

### ISSUE THREAD

**Issue by cmcantalupo** [LLNL/msr-safe#54]
@slabasan Any chance of getting a new tag out so we can update OpenHPC prior to the ISC release?

**Comment by slabasan** [comment]
Sure, we can do that. Since the last release, I believe the new changes would be (1) the spank plugin update, (2) updates to msrsave/restore, and (3) updating the writemask for TURBO_RATIO_LIMITS. Are there any other critical updates needed for the OpenHPC package?

**Comment by cmcantalupo** [comment]
I think everything I know of that we need has been merged to master.  Those issues that you mentioned being the important ones.

**Comment by slabasan** [comment]
Sounds good, what's your estimated timeframe for the ISC release? I can get a release of msr-safe out next week if that works with your timeline.

**Comment by cmcantalupo** [comment]
I think that should be fine.  It is really the openhpc maintainers that determine the timeline: @crbaird.

Since we have open pull requests from November 2 for updating to msr-safe 1.2.1 and updating the msr-safe slurm plugin package, it is hard to say how long it will take to update OpenHPC once the msr-safe tag is made.

**Comment by slabasan** [comment]
@cmcantalupo Latest release of msr-safe has been completed. Closing this ticket, and let us know if you need anything further for ISC.

**Comment by cmcantalupo** [comment]
Thanks @slabasan!
