### ISSUE TITLE
Wrong turbo ratio registers for 06_55 platform

### ISSUE THREAD

**Issue by vysocky** [LLNL/msr-safe#67]
06_55 platform does not have `MSR_TURBO_RATIO_LIMIT1 (0x1AE)` and `MSR_TURBO_RATIO_LIMIT2 (0x1AF)` registers, however the architecture has `MSR_TURBO_RATIO_LIMIT_CORES (0x1AE)` register.

https://github.com/LLNL/msr-safe/blob/master/whitelists/wl_0655#L33

See [Intel® 64 and IA-32 Architectures Software Developer’s Manual -  325462-071US](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf) table 2-45 (page 4845)

**Comment by slabasan** [comment]
This has been merged, thanks @vysocky for notifying us of the wrong MSRs!
